config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: 'items#index'
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :items do
    resources :transactions, only: [:show, :new, :create]
    resources :reviews, only:[:show, :new, :create]
    resources :devolutions, only:[:create]
  end

  resources :transactions, only: [:index]

  get "/panel", to: "users#panel", as: :panel
  get "/profile", to: "users#profile", as: :profile

  get "/transactions/:id/confirmed/:id", to: "transactions#confirmed", as: :confirmed
  post "/transactions/:id/new_budget", to: "transactions#new_budget", as: :new_budget

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :transactions
  has_many :reviews, dependent: :destroy
  validates :category, inclusion: { in: ["Console", "Jogo"], message: "Not a valid type" }
  validates :console_model, presence: true
  mount_uploader :photo, PhotoUploader
  validates :photo, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :items

  has_many :reviews, through: :items

  has_many :transactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  after_action :verify_authorized, except: [:index, :new_budget, :confirmed], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || items_path
  end


  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def create

  end
end

app/controllers/devolutions_controller.rb
class DevolutionsController < ApplicationController
  before_action :set_item, only: [:new, :create]
  before_action :set_transaction, only: [:new, :create]

  def new
  end

  def create
    @item.available = true
    @item.save
    @transaction.devoluted = true
    @transaction.save
    redirect_to transactions_path
  end

  private

  def set_item
    @item = Item.find(params[:item_id])
    authorize @item
  end

  def set_transaction
    @transaction = Transaction.find(params[:format])
    authorize @transaction
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy, :return]

  def index
    if params[:category] == "console"
      @items = Item.where(category: "Console").page(params[:page]).per(12)
    elsif params[:category] == "jogo"
      @items = Item.where(category: "Jogo").page(params[:page]).per(12)
    else
      @items = Item.all.page(params[:page]).per(12)
    end
    @items = @items.where(available: true)
    policy_scope(@items)
  end

  def show
  end

  def new
    @item = Item.new
    @item.category = params[:category]
    # if params[:category] == "Console"
    #   @item.game_title = ""
    # end
    authorize @item
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    authorize @item
    if @item.save
      redirect_to item_path(@item)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @item.update(item_params)
    redirect_to item_path(@item)
  end

  def destroy
    @item.destroy
    redirect_to items_path
  end

  private

  def set_item
    @item = Item.find(params[:id])
    authorize @item
  end

  def item_params
    params.require(:item).permit(:console_model, :game_title, :category, :price, :user_id, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_item, only: [:new, :create]

  def index
    @reviews = policy_scope(Review)
  end

  def show
    @review = Review.find(params[:item_id])
    authorize @review
  end

  def new
    @review = Review.new
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @review.item = @item
    @review.user = current_user
    authorize @review
    if @review.save
      redirect_to item_path(@item)
    else
      flash[:alert] = "Something went wrong."
      render :new
    end
  end

  private

  def set_item
    @item = Item.find(params[:item_id])
    authorize @item
  end

  def review_params
    params.require(:review).permit(:content, :rating, :item_id)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_item, only: [:new, :create]
  def index
    @transactions = policy_scope(Transaction).includes(:item).where(user: current_user).order(:created_at)
  end

  def show
    @transaction = Transaction.find(params[:id])
    authorize @transaction
  end

  def new
    @transaction = Transaction.new
    authorize @transaction
  end

  def create
    @transaction = Transaction.new(transaction_params)
    start_date = @transaction.start_date.to_date
    end_date = @transaction.end_date.to_date
    @transaction.cost = [1, ((end_date - start_date).to_i)].max * @item.price
    @transaction.item = @item
    @transaction.user = current_user
    @transaction.devoluted = false
    authorize @transaction
    if @transaction.save
      @item.available = false
      @item.save
      redirect_to item_transaction_path(@item, @transaction)
    else
      render :new
    end
  end

  def new_budget
    @transaction = Transaction.find(params[:id])
    @item = @transaction.item
    @item.available = true
    @item.save
    @transaction.destroy
    redirect_to new_item_transaction_path(@item)
  end

  def confirmed
    @transaction = Transaction.find(params[:id])
  end

  def confirmation
  end

  private

  def set_item
    @item = Item.find(params[:item_id])
    authorize @item
  end

  def transaction_params
    params.require(:transaction).permit(:start_date, :end_date, :item_id, :devoluted)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :set_user

  def profile

  end

  def panel
    @my_items = @user.items
    @boooked_items = @user.items.where(available: false)
  end

  private

  def set_user
    @user = current_user
    authorize @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_form.html.erb
<div>
<%= simple_form_for(@item) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs" style="width: 600px; margin: 0 auto; padding-top: 30px;">
    <% if params[:category] == "Console" %>
      <%= f.input :category, input_html: { value: 'Console' }, as: :hidden %>
      <%= f.input :game_title, input_html: { value: '' }, as: :hidden %>
      <%= f.input :console_model, label: "Modelo do Console:" %>
    <% else %>
      <%= f.input :category, input_html: { value: 'Jogo' }, as: :hidden %>
      <%= f.input :game_title, label: "Nome do Jogo:" %>
      <%= f.input :console_model, label: "Modelo do Console:" %>
    <% end %>
    <%= f.input :price, label: "Preço / dia (R$):" %>
    <%= f.input :photo, label: "Baixar foto:" %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>

  <div class="form-actions" style="width: 600px; margin: 0 auto; padding-top: 30px;">
    <%= f.button :submit, value: "Adicionar", class: "btn btn-outline-success" %>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class="container-dois products-container ">
  <div id="typed-strings">
      <p>EDITAR ITEM_</p>
  </div>
  <span id="typed"></span>
  <%= render 'form', item: @item %>

  <%= link_to 'Voltar à página do item', @item %> |
  <%= link_to 'Voltar à página principal', items_path %>
</div>

app/views/items/index.html.erb
<div class="container products-container ">
  <div class="py-3">
    <p>
      <span style="font-family: 'Orbitron', sans-serif;">Filtre por</span>
      <%= link_to 'Consoles', items_path(category: "console"), class: 'btn btn-outline-primary ml-3' %>
      <%= link_to 'Jogos', items_path(category: "jogo"), class: 'btn btn-outline-primary' %>
      <%= link_to 'Todos', items_path, class: 'btn btn-outline-primary' %>
    </p>

  </div>
  <div class="cards">
    <% @items.each do |item| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(
       <%= cl_image_path item.photo, height: 400, width: 600, crop: :fill %>)">
      <div>
        <% if item.game_title == "" %>
          <h3> <%= link_to item.console_model, item_path(item), class: "a-deco" %></h3>
          <p class="xs-small-card">Diária: R$ <%= item.price %></p>
        <% else %>
          <h3> <%= link_to item.game_title, item_path(item), class: "a-deco" %></h3>
          <p class="xs-small-card"> <%= item.console_model %></p>
          <p class="xs-small-card">Diária: R$ <%= item.price %></p>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/items/new.html.erb
<div class="container-dois products-container ">
  <div class="card">
    <div class="card-header text-center">
      <div id="typed-strings">
          <p>ADICIONAR ITEM_</p>
      </div>
      <span id="typed"></span>
    </div>
    <div class="card-body">
      <%= render 'form', item: @item %>
    </div>
  </div>

  <div style="width: 600px; margin: 0 auto; top: 40px;">
    <a> <%= link_to "Voltar à página principal", items_path, class: "links"%></a>
  </div>
  <br>
</div>

app/views/items/show.html.erb
<div class="container-dois products-container ">
  <div class="card-product">
    <%= cl_image_tag @item.photo, height: 300, width: 400, crop: :fill %>
    <div class="card-product-infos">
        <% if @item.game_title == "" %>
          <h1><%= @item.console_model %></h1>
        <% else %>
          <h1><%= @item.game_title %></h1>
        <% end %>
        <% if @item.game_title == "" %>
          <h2><%= "" %></h2>

        <% else %>
          <h5><strong>Console</strong> <%= @item.console_model %></h5>
        <% end %>

      <h5 class="card-title"><strong>Categoria </strong><%= @item.category %></h5>

      <h5 class="card-text"><strong>Preço </strong> R$<%= @item.price %> / dia</h5>

      <h5 class="card-text"><strong>Proprietário </strong><%= @item.user.first_name %> <%= @item.user.last_name %></h5>
    </div>
  </div>
      <br>
      <div class='form-inline' >

      <% if policy(@item).not_owner? %>
        <a><%= link_to "Alugar Item", new_item_transaction_path(@item), class: "btn btn-outline-success mr-3" %></a>
      <% end %>
      <br>
      <% if policy(@item).not_owner? %>
        <a><%= link_to "Nova Avaliação", new_item_review_path(@item), class: "btn btn-outline-success" %></a>
      <% end %>
      </div>

      <br>
       <!--  REVIEWS -->
      <div>

        <h4>Avaliações</h4>
        <% @item.reviews.each do |review|%>
          <div class="notification">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/#{review.user.email.split("@").first}", class: "avatar-large" %>
            <div class="notification-content">
              <p><small><%= review.created_at.strftime("%B %d, %Y") %> <% review.rating.times do %>⭐<%end%></small></p>
              <p><%= review.content %></p>
            </div>

            <div class="notification-actions">
              <a href="#">Edit <i class="fas fa-pencil-alt"></i></a>
              <a href="#">Delete <i class="far fa-trash-alt"></i></a>
            </div>
          </div>
        <% end %>
      </div>

      <br>

      <a><%= link_to "Voltar à página principal", items_path, class: "links" %></a>
        <% if policy(@item).update? %>
          <% if @item.category == "Console"  %>
            <a> | <%= link_to "Editar", edit_item_path(category: "Console"), class: "links" %></a>
          <% else %>
            <a> | <%= link_to "Editar", edit_item_path(category: "Jogo"), class: "links" %> | </a>
        <% end %>

          <a> <%= link_to "Deletar", item_path(@item), method: :delete, data: { confirm: "Tem certeza de quer deletar este item?" }, class: "links" %></a>
        <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Rent-a-rcade</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <footer>
      <%= render 'shared/footer' %>
    </footer>
  </body>
</html>

app/views/pages/home.html.erb
<!-- HOME LOGOUT-->
<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active" >
      <%= image_tag "image2.jpg", class: "d-flex w-100 carousel-img", alt: "First slide"%>
      <div class="carousel-caption text-left carousel-placement">
        <h1>Cansado de jogar os mesmos jogos?</h1>
        <p>Registre-se e alugue agora mesmo um novo jogo.</p>
        <p><a href="#" role="button"><%= link_to "Alugue agora!", new_user_registration_path, class: "btn btn-lg btn-success" %></a></p>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag "image.jpg", class: "d-block w-100 carousel-img", alt: "Second slide"%>
      <div class="carousel-caption text-left carousel-placement">
        <h1>Tem um videogame parado em casa?</h1>
        <p>Registre-se e ganhe dinheiro alugando seu console.</p>
        <p><a href="#" role="button"><%= link_to "Alugue agora!", new_user_session_path, class: "btn btn-lg btn-success" %></a></p>
      </div>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<!-- HOME THIERRY -->
<div class="container products-container">
  <ul class="nav nav-tabs ml-3" id="myTab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="console-tab" data-toggle="tab" href="#console" role="tab" aria-controls="console" aria-selected="true">Console</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="games-tab" data-toggle="tab" href="#games" role="tab" aria-controls="games" aria-selected="false">Games</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="games-console-tab" data-toggle="tab" href="#games-console" role="tab" aria-controls="games-console" aria-selected="false">Games and Console</a>
    </li>
  </ul>

  <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="console" role="tabpanel" aria-labelledby="console-tab">
        <div class="template py-4">
          <div class="template-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1532219600601-8494408a4a2c?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=400&ixid=eyJhcHBfaWQiOjF9&ixlib=rb-1.2.1&q=80&w=600)">
            X-Box
          </div>
        </div>
      </div>
      <div class="tab-pane fade grid" id="games" role="tabpanel" aria-labelledby="games-tab">
        <div class="template py-4">
          <div class="template-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1532219600601-8494408a4a2c?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=400&ixid=eyJhcHBfaWQiOjF9&ixlib=rb-1.2.1&q=80&w=600)">
            Sonic
          </div>
        </div>
      </div>
      <div class="tab-pane fade grid" id="games-console" role="tabpanel" aria-labelledby="games-console-tab">
        <div class="template py-4">
          <div class="template-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1532219600601-8494408a4a2c?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=400&ixid=eyJhcHBfaWQiOjF9&ixlib=rb-1.2.1&q=80&w=600)">
            X-Box
          </div>
        </div>
      </div>
  </div>
</div>

app/views/pages/my_account.html.erb
<% @items.each do |item| %>
  <% if item.game_title == "" %>
    <h2><%= link_to item.console_model, item_path(item) %><h2>
  <% else %>
    <h2><%= link_to item.game_title, item_path(item) %></h2>
  <% end %>
  <% if item.game_title == "" %>
    <h3><%= "" %><h2>
  <% else %>
    <h3>Console: <%= item.console_model %></h3>
  <% end %>
  <p>Categoria: <%= item.category %></p>
  <p>R$<%= item.price %> / dia</p>
  <br>
<% end %>

app/views/reviews/new.html.erb
<div class="container products-container">
  <div id="typed-strings">
      <p>Avaliação
_</p>
  </div>
  <span id="typed"></span>

  <div class="row">
    <div class="offset-md-3 col-md-6 border mt-5 py-5">
      <%= simple_form_for [@item, @review], html: { class: "review_form" } do |f| %>
        <%= f.input :content, label:"Conte-me mais sobre o game..." %>
        <%= f.input :rating, collection: (1..5).to_a, label: "Avalie sua experiência" %>
        <%= f.submit "Enviar", class: "d-none" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <h2 class="title-nav" style="font-family: VT323;">RENT-A-RCADE</h2>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Adicionar console", new_item_path(category: "Console"), class: "btn btn-outline-success nav-link mr-2" %>
        </li>
        <li class="nav-item">
          <%= link_to "Adicionar jogo", new_item_path(category: "Jogo"), class: "btn btn-outline-success nav-link mr-2" %>
        </li>
        <li class="nav-item">
          <%= link_to "Home", items_path, class: "nav-link" %>
        </li>
        <li class="nav-item mr-2">
          <%= link_to "Reservas", transactions_path, class: "nav-link" %>
        </li>
        <li class="nav-item mr-2">
          <%= link_to "Anúncios", panel_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/#{current_user.email.split("@").first}", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Perfil", profile_path, class: "dropdown-item" %>
            <%= link_to "Configurações", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/transactions/index.html.erb
<div class="container products-container  bg-white">
  <div id="typed-strings">
      <p>Reservas_</p>
  </div>
  <span id="typed"></span>

  <div class="container bg-white justify-content-center">
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col" class="table-title">ID</th>
          <th scope="col" class="table-title">CONSOLE</th>
          <th scope="col" class="table-title">JOGO</th>
          <th scope="col" class="table-title">VALOR</th>
          <th scope="col" class="table-title"></th>
          <th scope="col" class="table-title"></th>
          <th scope="col" class="table-title"></th>
        <br>
        </tr>
      </thead>
      <tbody>
        <% @transactions.each_with_index do |transaction, index| %>
          <tr>
            <th scope="row"><%= transaction.id %></th>
            <td><%= transaction.item.console_model %></td>
            <td><%= transaction.item.game_title %></td>
            <td>R$<%= transaction.cost %></td>
            <td><%= link_to "Detalhes", confirmed_path(transaction.item, transaction), class: "btn btn-outline-success" %></td>
            <td><%= link_to "Avaliar", new_item_review_path(transaction.item), class: "btn btn-outline-success" %></td>
            <td>
              <% if !transaction.item.available && !transaction.devoluted %>
                <%= link_to "Devolver", item_devolutions_path(transaction.item, transaction.id), class: "btn btn-outline-success", method: :post %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/transactions/show.html.erb
<div class="container-dois">
    <div id="typed-strings">
        <p>Revisar_</p>
    </div>
    <span id="typed"></span>
  <br>
  <div class="card" style="width: 40rem; border: none">
    <ul class="list-group list-group-flush">
      <li class="list-group-item"><b><%= @transaction.item.category.upcase %></b> <%= @transaction.item.console_model %> - <%= @transaction.item.game_title %></li>
      <li class="list-group-item">De <%= l @transaction.start_date, format: "%d de %B de %Y" %> até <%= l @transaction.end_date, format: "%d de %B de %Y" %></li>
      <li class="list-group-item">R$ <%= @transaction.item.price %> x <%= ((@transaction.end_date - @transaction.start_date)/1.day).round %> dia(s)</li>
      <li class="list-group-item">Total: R$ <%= @transaction.cost %></li>
    </ul>
  </div>
  <br>
      <%= link_to "Confirmar", confirmed_path(@transaction), class: "btn btn-outline-success mb-2 mr-sm-2" %>
      <%= link_to "Novo orçamento", new_budget_path(@transaction), class: "btn btn-outline-success mb-2 mr-sm-2", method: :post %>
</div>

app/views/users/panel.html.erb
<div class="products-container">
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="container">
        <div id="typed-strings">
          <p>Reservas_</p>
        </div>
        <span id="typed"></span>

        <div class="card bg-white justify-content-center">
          <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col" class="table-title">RESERVA</th>
                <th scope="col" class="table-title">CONSOLE</th>
                <th scope="col" class="table-title">JOGO</th>
                <th scope="col" class="table-title">VALOR</th>
                <th scope="col" class="table-title">
                JOGADOR</th>
                <th scope="col" class="table-title"></th>
                <th scope="col" class="table-title"></th>
              </tr>
            </thead>
            <tbody>
              <% @boooked_items.each do |item| %>
                <tr>
                  <th scope="row"><%= item.transactions.last.id %></th>
                  <td><%= item.console_model %></td>
                  <td><%= item.game_title %></td>
                  <td>R$<%= item.transactions.last.cost %></td>
                  <td><%= item.transactions.last.user.email %></td>
                  <td><a><%= link_to "Detalhes", class: "btn btn-outline-success" %></a>
                  <a><%= link_to "Devolver",class: "btn btn-outline-success" %></a></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="col-6">
      <div class="container">
        <div class="listings">
          <div id="typed-strings2">
            <p>Anúncios_</p>
          </div>
          <span id="typed2"></span>

          <div class="card bg-white justify-content-center">
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th scope="col" class="table-title">ID</th>
                    <th scope="col" class="table-title">ITEM</th>
                    <th scope="col" class="table-title">CATEGORIA</th>
                    <th scope="col" class="table-title">VALOR (R$/DIA)</th>
                    <th scope="col" class="table-title"></th>
                  </tr>
                </thead>
                <tbody>
                  <% @my_items.each do |item| %>
                    <tr>
                      <th scope="row"><%= item.id %></th>
                      <% if item.game_title == "" %>
                        <td><%= item.console_model %></td>
                      <% else %>
                        <td><%= item.game_title %></td>
                      <% end %>
                      <td><%= item.category %></td>
                      <td><%= format("%.2f", item.price) %></td>
                      <td>
                        <% if policy(item).update? %>
                          <% if item.category == "Console" %>
                            <a href="#" role="button"><%= link_to "Editar", edit_item_path(id: item, category: "Console"), class: "btn btn-outline-success" %></a>
                          <% else %>
                            <a href="#" role="button"><%= link_to "Editar", edit_item_path(id: item, category: "Jogo"), class: "btn btn-outline-success" %></a>
                          <% end %>
                          <a href="#" role="button"><%= link_to "Deletar", item_path(item), method: :delete, data: { confirm: "Tem certeza de quer deletar este item?" }, class: "btn btn-outline-success" %></a>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
          </div>
        </div>
      </div>
    </div>
</div>